resources:
  apps:
    hello-world-app:
      name: "hello-world-app"
      source_code_path: ../src/app
      description: "A Streamlit app that lets users trigger the job included in this bundle."
      config:
        command:
          - "streamlit"
          - "run"
          - "app.py"
        env:
          - name: JOB_ID
            value: ${resources.jobs.hello_world.id}

      resources:
        - name: "app-job"
          description: "A job that can be invoked by this app."
          job:
            id: ${resources.jobs.hello_world.id}
            permission: "CAN_MANAGE_RUN"
